gamepad_to_ackermann_node:
  ros__parameters:
    joy_topic: "/joy"
    ackermann_topic: "/ackermann_cmd"
    frame_id: "base_link"

    steering_axis_index: 0
    forward_button_index: 1
    reverse_button_index: 3

    max_steer_rad: 0.24
    max_forward_speed_mps: 0.2
    max_reverse_speed_mps: 0.1
    accel_mps2: 0.4
    steering_deadzone: 0.05
    invert_steering: true

    publish_rate_hz: 30.0
    joy_timeout_ms: 300
    debug_print: false
